### ISSUE TITLE
Different images to pop up on "hit"

### ISSUE THREAD

**Issue by charmgeorge** [charmgeorge/Day-15-BattleShip#1]
I would like a different artist/band's image to show up for every "hit". It is currently set up so only Adele's image shows when there is a "hit". Multiple "hits" show multiple images of Adele. How can I set it up so each hit is a different image? @bethgrace5

**Comment by bethgrace5** [comment]
@charmgeorge Instead of putting the background image URL in the class, you could directly assign it to the style of the element on "hit". 

So I would update the `.hit` class to not set the url like so:
```
.hit{
  background-size: 80px 60px;
}
```

Then, when you find a "hit", you can directly set the element's style like so:
```
e.target.className="hit";
e.target.style="background-image: url('images/adele.jpg')";
```
This was how I could think to accomplish this task with plain javascript/html. I'll let you see where you can take it from there. Let me know if you figure out any other cool ways to accomplish this. Tag me if you have any questions.

**Comment by charmgeorge** [comment]
@bethgrace5 thank you! I will try this.
